const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {URL}=require('url');
const ROOT=__dirname,PUBLIC=path.join(ROOT,'public'),DATA=process.env.DATA_FILE||path.join(ROOT,'data.json'),PRIVATE=path.join(ROOT,'private','engine.json'),PORT=Number(process.env.PORT||3000);
const FRONTEND_ORIGINS=(process.env.FRONTEND_ORIGIN||'').split(',').map(x=>x.trim()).filter(Boolean);
const isProduction=process.env.NODE_ENV==='production';
const adminEmail=String(process.env.ADMIN_EMAIL||(isProduction?'':'admin@tradecraft.local')).trim().toLowerCase();
const adminPassword=String(process.env.ADMIN_PASSWORD||(isProduction?'':'Admin@123'));
if(isProduction&&!process.env.FRONTEND_ORIGIN)throw new Error('Production deployment requires FRONTEND_ORIGIN.');
if(isProduction&&(!process.env.ADMIN_EMAIL||!process.env.ADMIN_PASSWORD))throw new Error('Production deployment requires ADMIN_EMAIL and ADMIN_PASSWORD environment variables.');
const ENGINE=JSON.parse(fs.readFileSync(PRIVATE,'utf8'));
const COMPANIES=[
 {ticker:'TAVR',name:'Tavros Energy',sector:'Energy',start:84.50,volatility:'High',color:'#f59e0b'},
 {ticker:'AERV',name:'Aerovia Airlines',sector:'Air Travel',start:42.80,volatility:'Very High',color:'#38bdf8'},
 {ticker:'VLTN',name:'Vaultline Bank',sector:'Banking',start:126.40,volatility:'Moderate',color:'#a78bfa'},
 {ticker:'BRKW',name:'Brickwell Developers',sector:'Property',start:58.90,volatility:'High',color:'#fb7185'},
 {ticker:'LMRA',name:'Lumora Labs',sector:'Technology',start:71.20,volatility:'Very High',color:'#34d399'},
 {ticker:'GRFD',name:'Greenfield Foods',sector:'Consumer Staples',start:95.60,volatility:'Low',color:'#facc15'}
];
const SENS={TAVR:{RATES:0,OIL:3,DEMAND:1,SENTIMENT:1},AERV:{RATES:-1,OIL:-3,DEMAND:3,SENTIMENT:2},VLTN:{RATES:3,OIL:0,DEMAND:2,SENTIMENT:2},BRKW:{RATES:-3,OIL:-1,DEMAND:2,SENTIMENT:2},LMRA:{RATES:-2,OIL:0,DEMAND:1,SENTIMENT:3},GRFD:{RATES:0,OIL:-1,DEMAND:1,SENTIMENT:-1}};
const VOL={TAVR:1.1,AERV:1.3,VLTN:.9,BRKW:1.0,LMRA:1.6,GRFD:.5};
const SESSION_MS=12*60*60*1000;let db,timer=null;const sessions=new Map(),streams=new Set();
const now=()=>new Date().toISOString(),id=()=>crypto.randomUUID();
function hash(p,s=crypto.randomBytes(16).toString('hex')){return s+':'+crypto.scryptSync(p,s,64).toString('hex')}
function verify(p,stored){try{const [s,k]=stored.split(':');return crypto.timingSafeEqual(crypto.scryptSync(p,s,64),Buffer.from(k,'hex'))}catch{return false}}
function baseDB(){return {settings:{eventName:'Market Sprint · Fictional Markets Edition',status:'lobby',tick:0,maxTicks:96,secondsPerTick:75,startedAt:null,closedAt:null,headlineCount:0},users:[{id:'admin-001',name:'Event Control',email:adminEmail,role:'admin',password:hash(adminPassword)}],teams:[],prices:Object.fromEntries(COMPANIES.map(c=>[c.ticker,c.start])),history:[],orders:[],pending:[],news:[],audit:[{time:now(),actor:'system',action:'SYSTEM_READY',detail:'Organizer control plane initialized'}],locks:{}}}
function load(){try{const parent=path.dirname(DATA);fs.mkdirSync(parent,{recursive:true});db=fs.existsSync(DATA)?JSON.parse(fs.readFileSync(DATA,'utf8')):baseDB()}catch{db=baseDB()} db.users??=[];db.teams??=[];db.orders??=[];db.pending??=[];db.news??=[];db.history??=[];db.audit??=[];db.settings??=baseDB().settings;db.prices??=Object.fromEntries(COMPANIES.map(c=>[c.ticker,c.start])); const admin=db.users.find(u=>u.role==='admin'&&u.email===adminEmail);if(admin){admin.password=hash(adminPassword);admin.name='Event Control'}else db.users.push({id:'admin-001',name:'Event Control',email:adminEmail,role:'admin',password:hash(adminPassword)}); persist()}
function persist(){const tmp=DATA+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,DATA)}
function backup(){const dir=path.join(ROOT,'backups');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,`snapshot-${Date.now()}.json`),JSON.stringify(db,null,2))}
function audit(actor,action,detail){db.audit.unshift({time:now(),actor,action,detail});db.audit=db.audit.slice(0,600)}
function value(t){return Number((t.cash+Object.entries(t.holdings||{}).reduce((s,[k,q])=>s+q*(db.prices[k]||0),0)).toFixed(2))}
function availableCash(t){return Number((t.cash-(t.reservedCash||0)).toFixed(2))}
function availableQty(t,k){return Math.max(0,(t.holdings?.[k]||0)-(t.reservedHoldings?.[k]||0))}
function teamPublic(t){return {...t,value:value(t),availableCash:availableCash(t),eligible:t.trades>=6&&t.companiesTraded.length>=3}}
function publicState(){const scheduled=ENGINE.events.filter(e=>e.type==='Scheduled').map(e=>({id:e.id,tick:e.tick,type:e.type,headline:'Scheduled market event',forecast:e.forecast||'Forecast available on event calendar',published:false}));return {settings:db.settings,prices:db.prices,companies:COMPANIES.map(({color,...c})=>c),history:db.history.slice(-100),news:db.news.filter(n=>n.published).slice(0,40),calendar:scheduled}}
function broadcast(){const payload=`data: ${JSON.stringify(publicState())}\n\n`;for(const s of [...streams]){try{s.write(payload)}catch{streams.delete(s)}}}
function eventAt(tick){return ENGINE.events.find(e=>e.tick===tick)}
function eventPercent(e,ticker){let impact=0;for(const d of ['RATES','OIL','DEMAND','SENTIMENT'])impact+=(SENS[ticker][d]||0)*(e.shock?.[d]||0);let pct=impact*VOL[ticker];if(e.companyMoves?.[ticker])pct+=e.companyMoves[ticker];return pct}
function profileFor(e,ticker){if(e.profile?.[ticker])return e.profile[ticker]; if(e.type==='Surprise'&&['E10','E12'].includes(e.id))return 'Spike-and-fade'; if(['E03','E14'].includes(e.id))return 'Slow burn'; return 'Step'}
const PROFILES={Step:[.2,.6,.9,1,1,1],'Spike-and-fade':[.3,.8,1.2,1,.8,.6],'Slow burn':[.1,.25,.45,.65,.85,1]};
function buildSeries(){const series=Object.fromEntries(COMPANIES.map(c=>[c.ticker,Array(97).fill(c.start)]));const pending=Object.fromEntries(COMPANIES.map(c=>[c.ticker,[]]));for(const e of ENGINE.events){for(const c of COMPANIES){const pct=eventPercent(e,c.ticker);if(!pct)continue;const profile=PROFILES[profileFor(e,c.ticker)]||PROFILES.Step;for(let i=1;i<=6;i++){const tick=e.tick+i;if(tick>96)break;pending[c.ticker].push({tick,delta:pct*profile[i-1]/100});}}}for(const c of COMPANIES){let p=c.start;for(let tick=1;tick<=96;tick++){let delta=0;for(const x of pending[c.ticker])if(x.tick===tick)delta+=x.delta;const noise=(Math.sin(tick*.73+c.ticker.charCodeAt(0))*VOL[c.ticker]*.12+Math.sin(tick*.19)*VOL[c.ticker]*.05)/100;p=Math.max(5,p*(1+delta+noise));series[c.ticker][tick]=Number(p.toFixed(2))}}return series}
let LOCKED_SERIES=buildSeries();
function fillOrders(tick){const ready=db.pending.filter(o=>o.executeTick<=tick);db.pending=db.pending.filter(o=>o.executeTick>tick);for(const o of ready){const t=db.teams.find(x=>x.id===o.teamId);if(!t)continue;const p=db.prices[o.ticker];const gross=Number((p*o.quantity).toFixed(2));const fee=Number((gross*.004).toFixed(2));if(o.side==='BUY'){t.reservedCash=Math.max(0,(t.reservedCash||0)-o.reserve);t.cash=Number((t.cash-gross-fee).toFixed(2));t.holdings[o.ticker]=(t.holdings[o.ticker]||0)+o.quantity}else{t.reservedHoldings[o.ticker]=Math.max(0,(t.reservedHoldings[o.ticker]||0)-o.quantity);t.cash=Number((t.cash+gross-fee).toFixed(2));t.holdings[o.ticker]=(t.holdings[o.ticker]||0)-o.quantity}t.trades++;if(!t.companiesTraded.includes(o.ticker))t.companiesTraded.push(o.ticker);db.orders.unshift({...o,price:p,fee,total:o.side==='BUY'?gross+fee:gross-fee,executionTick:tick,status:'filled',filledAt:now()});audit(t.name,'ORDER_FILLED',`${o.side} ${o.quantity} ${o.ticker} @ V ${p.toFixed(2)}`)}}
function step(force=false){if(db.settings.status!=='running'&&!force)return false;if(db.settings.tick>=96)return false;db.settings.tick++;const tick=db.settings.tick;for(const c of COMPANIES)db.prices[c.ticker]=LOCKED_SERIES[c.ticker][tick];const e=eventAt(tick);if(e){db.news.unshift({id:e.id,tick,type:e.type,title:e.headline,forecast:e.forecast||'',published:true,time:now()});db.news=db.news.slice(0,40);db.settings.headlineCount++;audit('system','NEWS_FIRED',`Tick ${tick} · ${e.headline}`)}fillOrders(tick);db.history.push({tick,time:now(),prices:{...db.prices}});db.history=db.history.slice(-120);if(tick===96){db.settings.status='closed';db.settings.closedAt=now();stop();audit('system','MARKET_CLOSED','Closing tick reached')}persist();broadcast();return true}
function start(){stop();timer=setInterval(()=>step(),db.settings.secondsPerTick*1000)}function stop(){if(timer){clearInterval(timer);timer=null}}
load();if(db.settings.status==='running')start();
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>2e6)reject(new Error('Body too large'))});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch{reject(new Error('Invalid JSON'))}})})}
function cookie(req){return req.headers.cookie?.match(/(?:^|;\s*)tc_session=([^;]+)/)?.[1]||null}
function user(req){const s=sessions.get(cookie(req));if(!s||s.exp<Date.now())return null;return db.users.find(u=>u.id===s.uid)||null}
function auth(req,res,role){const u=user(req);if(!u)return fail(res,401,'Authentication required');if(role&&u.role!==role)return fail(res,403,'Forbidden');return u}
function applyCors(req,res){const origin=req.headers.origin;if(origin&&FRONTEND_ORIGINS.includes(origin)){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Credentials','true');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS')}}
function send(res,status,data,extra={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...extra});res.end(JSON.stringify(data))}
function fail(res,status,error){send(res,status,{error})}
const routes=new Map();const R=(m,p,f)=>routes.set(m+' '+p,f);
R('POST','/api/login',async(req,res)=>{const b=await body(req),email=String(b.email||'').trim().toLowerCase(),u=db.users.find(x=>x.email===email);if(!u||!verify(String(b.password||''),u.password))return fail(res,401,'Invalid email or password');const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{uid:u.id,exp:Date.now()+SESSION_MS});res.setHeader('Set-Cookie',`tc_session=${token}; HttpOnly; ${isProduction?'Secure; SameSite=None;':'SameSite=Lax;'} Path=/; Max-Age=${SESSION_MS/1000}`);audit(u.name,'LOGIN','Successful sign in');persist();send(res,200,{user:{id:u.id,name:u.name,email:u.email,role:u.role,teamCode:u.teamCode||null}})});
R('POST','/api/logout',(req,res)=>{sessions.delete(cookie(req));res.setHeader('Set-Cookie',`tc_session=; HttpOnly; ${isProduction?'Secure; SameSite=None;':'SameSite=Lax;'} Path=/; Max-Age=0`);send(res,200,{ok:true})});
R('GET','/api/me',(req,res)=>{const u=user(req);if(!u)return fail(res,401,'Not signed in');send(res,200,{user:{id:u.id,name:u.name,email:u.email,role:u.role,teamCode:u.teamCode||null}})});
R('GET','/api/health',(req,res)=>send(res,200,{ok:true,service:'tradecraft-api',status:db.settings.status,tick:db.settings.tick}));
R('GET','/api/market',(req,res)=>send(res,200,publicState()));
R('GET','/api/stream',(req,res)=>{res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.write(`data: ${JSON.stringify(publicState())}\n\n`);streams.add(res);req.on('close',()=>streams.delete(res))});
R('GET','/api/leaderboard',(req,res)=>send(res,200,{leaderboard:db.teams.map(teamPublic).sort((a,b)=>b.value-a.value).map((t,i)=>({...t,rank:i+1})) ,settings:db.settings}));
R('GET','/api/team',(req,res)=>{const u=auth(req,res,'team');if(!u)return;const t=db.teams.find(x=>x.id===u.id);if(!t)return fail(res,404,'Team account not found');send(res,200,{team:teamPublic(t),companies:COMPANIES,prices:db.prices,settings:db.settings,history:db.history.slice(-100),orders:db.orders.filter(o=>o.teamId===t.id).slice(0,50),pending:db.pending.filter(o=>o.teamId===t.id),news:db.news.filter(n=>n.published).slice(0,20),calendar:publicState().calendar})});
R('POST','/api/team/order',async(req,res)=>{const u=auth(req,res,'team');if(!u)return;const b=await body(req),t=db.teams.find(x=>x.id===u.id),ticker=String(b.ticker||'').toUpperCase(),side=String(b.side||'').toUpperCase(),qty=Number(b.quantity);if(db.settings.status!=='running')return fail(res,409,'Trading is not open');if(!COMPANIES.some(c=>c.ticker===ticker)||!['BUY','SELL'].includes(side)||!Number.isInteger(qty)||qty<=0)return fail(res,400,'Invalid order');if(t.trades+db.pending.filter(o=>o.teamId===t.id).length>=22)return fail(res,409,'22-trade limit reached');const last=t.lastOrderAt?Date.parse(t.lastOrderAt):0;if(Date.now()-last<7000)return fail(res,429,'Please wait 7 seconds between orders');const p=db.prices[ticker],portfolio=value(t),gross=p*qty,fee=gross*.004;if(side==='BUY'){if(gross>portfolio*.35+0.01)return fail(res,409,'BUY exceeds the 35% portfolio limit');if(availableCash(t)<gross+fee)return fail(res,409,'Insufficient available V-Coins');const after=t.holdings[ticker]||0;const afterValue=after*p+gross;if(afterValue>portfolio*.60+0.01)return fail(res,409,'Company concentration would exceed 60%');t.reservedCash=(t.reservedCash||0)+gross+fee}else{if(availableQty(t,ticker)<qty)return fail(res,409,'Insufficient holdings');t.reservedHoldings??={};t.reservedHoldings[ticker]=(t.reservedHoldings[ticker]||0)+qty}t.lastOrderAt=now();const o={id:id(),teamId:t.id,side,ticker,quantity:qty,placedAt:now(),executeTick:Math.min(96,db.settings.tick+1),status:'pending',reserve:side==='BUY'?gross+fee:0};db.pending.push(o);audit(t.name,'ORDER_PLACED',`${side} ${qty} ${ticker} · fills tick ${o.executeTick}`);persist();broadcast();send(res,200,{message:`${side} order accepted · fills at tick ${o.executeTick}`,order:o})});
R('GET','/api/admin/overview',(req,res)=>{const u=auth(req,res,'admin');if(!u)return;send(res,200,{settings:db.settings,prices:db.prices,companies:COMPANIES,teams:db.teams.map(teamPublic),orders:db.orders.slice(0,80),pending:db.pending,audit:db.audit.slice(0,80),engineEvents:ENGINE.events.map(e=>({...e,published:e.tick<=db.settings.tick})),calendar:publicState().calendar})});
R('POST','/api/admin/start',(req,res)=>{const u=auth(req,res,'admin');if(!u)return;if(db.settings.status==='closed')return fail(res,409,'Market is already closed. Reset to run another session.');if(db.settings.status!=='running'){db.settings.status='running';db.settings.startedAt??=now();audit(u.name,'MARKET_STARTED',`Tick ${db.settings.tick}`);persist();start();broadcast()}send(res,200,{ok:true})});
R('POST','/api/admin/pause',(req,res)=>{const u=auth(req,res,'admin');if(!u)return;db.settings.status='paused';stop();audit(u.name,'MARKET_PAUSED',`Tick ${db.settings.tick}`);persist();broadcast();send(res,200,{ok:true})});
R('POST','/api/admin/tick',(req,res)=>{const u=auth(req,res,'admin');if(!u)return;const ok=step(true);if(!ok)return fail(res,409,'Cannot advance tick');audit(u.name,'MANUAL_TICK',`Advanced to tick ${db.settings.tick}`);persist();send(res,200,{ok:true,tick:db.settings.tick})});
R('POST','/api/admin/reset',(req,res)=>{const u=auth(req,res,'admin');if(!u)return;backup();stop();db=baseDB();LOCKED_SERIES=buildSeries();audit(u.name,'MARKET_RESET','Fresh event state created');persist();send(res,200,{ok:true})});
R('POST','/api/admin/team',async(req,res)=>{const u=auth(req,res,'admin');if(!u)return;const b=await body(req),name=String(b.name||'').trim(),email=String(b.email||'').trim().toLowerCase(),members=Math.max(1,Math.min(20,Number(b.members)||1)),password=String(b.password||'Team@123');if(!name||!email.includes('@'))return fail(res,400,'Team name and valid email required');if(db.users.some(x=>x.email===email))return fail(res,409,'Email already registered');const code=(name.replace(/[^A-Za-z0-9]/g,'').slice(0,5).toUpperCase()+Math.random().toString(36).slice(2,7).toUpperCase()).slice(0,10),uid=id();const t={id:uid,name,code,members,cash:10000,holdings:{},reservedCash:0,reservedHoldings:{},trades:0,companiesTraded:[],joinedAt:now()};db.users.push({id:uid,name,email,role:'team',teamCode:code,password:hash(password)});db.teams.push(t);audit(u.name,'TEAM_CREATED',`${name} · ${code}`);persist();send(res,200,{name,email,password,code})});
R('POST','/api/admin/news',async(req,res)=>{const u=auth(req,res,'admin');if(!u)return;const b=await body(req);if(!String(b.title||'').trim())return fail(res,400,'Headline required');db.news.unshift({id:id(),tick:db.settings.tick,type:b.type||'Manual',title:String(b.title).trim(),forecast:String(b.forecast||''),published:true,time:now(),manual:true});db.news=db.news.slice(0,40);audit(u.name,'MANUAL_NEWS',String(b.title).trim());persist();broadcast();send(res,200,{ok:true})});
R('GET','/api/admin/export',(req,res)=>{const u=auth(req,res,'admin');if(!u)return;send(res,200,{event:db.settings,teams:db.teams.map(teamPublic),orders:db.orders,news:db.news,audit:db.audit})});
async function handle(req,res){try{applyCors(req,res);if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}const u=new URL(req.url,`http://${req.headers.host}`),key=req.method+' '+u.pathname,f=routes.get(key);if(f)return await f(req,res);let p=decodeURIComponent(u.pathname);if(p==='/')p='/index.html';const file=path.join(PUBLIC,p);if(!file.startsWith(PUBLIC)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return fail(res,404,'Not found');const ext=path.extname(file),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(res)}catch(e){console.error(e);fail(res,500,'Server error')}}
http.createServer(handle).listen(PORT,()=>console.log(`TradeCraft running at http://localhost:${PORT}`));
